if(NOT INPUT_FILE OR NOT OUTPUT_FILE OR NOT TOP_N MATCHES "^[0-9]+$" OR TOP_N LESS 1)
    message(FATAL_ERROR "Supply INPUT_FILE, OUTPUT_FILE and a positive TOP_N")
endif()

file(STRINGS "${INPUT_FILE}" lines ENCODING UTF-8)
set(words "")
set(kept 0)
foreach(line IN LISTS lines)
    if(kept GREATER_EQUAL TOP_N)
        break()
    endif()
    if(NOT line MATCHES "^[0-9]+[ \t]+([A-Za-z]+)[ \t]+[0-9,]+")
        continue()
    endif()
    string(TOLOWER "${CMAKE_MATCH_1}" word)
    string(LENGTH "${word}" length)
    if(length GREATER 28 OR (length LESS 2 AND NOT word STREQUAL "a" AND NOT word STREQUAL "i"))
        continue()
    endif()
    string(APPEND words "${word}\n")
    math(EXPR kept "${kept} + 1")
endforeach()
if(NOT kept)
    message(FATAL_ERROR "No ranked English words found in ${INPUT_FILE}")
endif()
file(WRITE "${OUTPUT_FILE}" "${words}")
message(STATUS "Selected ${kept} English words")
